// Raw SVG lookup, isolated so only the functions that serve icon bodies bundle
// the (larger) svgs.json. Generated by scripts/generate-llm-manifest.ts.

import svgs from '../site/public/svgs.json' with { type: 'json' }

const SVGS = svgs as Record<string, string>

export function getSvg(name: string): string | undefined {
  return SVGS[name]
}
