import { readdir, writeFile } from 'node:fs/promises'

const sourceDir = new URL('../src/', import.meta.url)
const extensionPattern = /\.tsx$/
const files = (await readdir(sourceDir))
  .filter((file) => file.endsWith('.tsx'))
  .sort((left, right) => left.localeCompare(right))

const exports = files.map((file) => {
  const moduleName = file.replace(extensionPattern, '')

  return `export * from "./${moduleName}";`
})

const contents = [
  '// This file is generated by scripts/generate-index.mjs.',
  ...exports,
  '',
].join('\n')

await writeFile(new URL('../src/index.ts', import.meta.url), contents)
